/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#b0c6ff",
        "on-primary": "#002d6f",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        "secondary-container": "#454747",
        "on-background": "#e5e2e1",
        "outline-variant": "#424655",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "primary": "#b0c6ff",
        "tertiary-container": "#f36420",
        "secondary": "#c6c6c7",
        "on-secondary": "#2f3131",
        "on-tertiary-fixed-variant": "#7f2b00",
        "on-tertiary-container": "#4f1700",
        "inverse-on-surface": "#313030",
        "surface-bright": "#393939",
        "on-primary-fixed-variant": "#00429c",
        "inverse-primary": "#0058cb",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#370e00",
        "surface-variant": "#353534",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#b0c6ff",
        "on-surface-variant": "#c2c6d8",
        "tertiary": "#ffb599",
        "tertiary-fixed-dim": "#ffb599",
        "on-primary-container": "#002661",
        "primary-fixed": "#d9e2ff",
        "on-secondary-fixed-variant": "#454747",
        "on-tertiary": "#5a1c00",
        "tertiary-fixed": "#ffdbce",
        "error-container": "#93000a",
        "on-secondary-fixed": "#1a1c1c",
        "secondary-fixed-dim": "#c6c6c7",
        "outline": "#8c90a1",
        "primary-container": "#568dff",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#201f1f",
        "secondary-fixed": "#e2e2e2",
        "background": "#131313",
        "on-secondary-container": "#b4b5b5",
        "surface": "#131313",
        "on-primary-fixed": "#001945",
        "surface-dim": "#131313"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px",
        "container-max": "1440px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "caption": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "caption": ["12px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
